// netlify/functions/get-invoice.js
// GET /pay/:invoiceId?token=<secure_token>
//
// v3 FIXES:
// #1 - CommonJS (covered by functions/package.json "type":"commonjs")
// #2 - Validates the token that create-payment-link generated and stored
// #3 - ALLOWED_ORIGIN hard fails if missing in production
// #7 - Stripe only initialized if token validation passes (saves cold start time)

"use strict";

const { validateToken } = require("./create-payment-link");

exports.handler = async (event) => {
  const allowedOrigin = process.env.ALLOWED_ORIGIN;
  if (!allowedOrigin && process.env.NODE_ENV === "production") {
    return { statusCode: 500, body: JSON.stringify({ error: "Server misconfiguration" }) };
  }

  const headers = {
    "Access-Control-Allow-Origin": allowedOrigin || "*",
    "Access-Control-Allow-Headers": "Content-Type",
    "Content-Type": "application/json",
  };

  if (event.httpMethod === "OPTIONS") return { statusCode: 204, headers, body: "" };

  try {
    // Extract invoiceId from path: /pay/INV-1001
    const pathParts = (event.path || "").split("/").filter(Boolean);
    const invoiceId = decodeURIComponent(pathParts[pathParts.length - 1] || "");

    if (!invoiceId || invoiceId === "pay") {
      return { statusCode: 400, headers, body: JSON.stringify({ error: "Invoice ID is required" }) };
    }

    // Fix #2: Validate the secure token that was generated by create-payment-link
    const token = event.queryStringParameters?.token;
    if (!token) {
      return {
        statusCode: 401,
        headers,
        body: JSON.stringify({ error: "Access token required. Check your invoice email for the correct payment link." }),
      };
    }

    const tokenData = validateToken(invoiceId, token);
    if (!tokenData) {
      return {
        statusCode: 401,
        headers,
        body: JSON.stringify({ error: "Invalid or expired token. Please request a new invoice link from your warehouse." }),
      };
    }

    // Fix #7: Only initialize Stripe after token validation passes
    const Stripe = require("stripe");
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

    // Look up the payment link in Stripe
    const paymentLinks = await stripe.paymentLinks.list({ limit: 100 });
    const matchingLink = paymentLinks.data.find(
      pl => pl.metadata?.invoice_number === invoiceId && pl.active
    );

    if (!matchingLink) {
      return {
        statusCode: 404,
        headers,
        body: JSON.stringify({ error: "Invoice not found or payment link has expired." }),
      };
    }

    console.log(`Portal access granted: ${invoiceId} for ${tokenData.clientEmail}`);

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        invoiceId,
        paymentUrl: matchingLink.url,
        clientEmail: tokenData.clientEmail,
        active: matchingLink.active,
      }),
    };
  } catch (err) {
    console.error("get-invoice error:", err.message);
    return { statusCode: 500, headers, body: JSON.stringify({ error: "Failed to retrieve invoice" }) };
  }
};
